make mongo client configurable
JarnoRFB/incense pull request #83
Opened 2022-12-08 10:32 UTC by christian-steinmeyer

2022-12-08 11:21 UTC, christian-steinmeyer commented
Do I misinterpret the logs or is there some unrelated issue on CI?

2022-12-09 09:06 UTC, JarnoRFB requested changes
Thanks for the contribution! I will check what the problem with the CI is.

2022-12-09 09:06 UTC, JarnoRFB commented on incense/experiment_loader.py
> +    def __init__(self, mongo_uri=None, db_name="sacred", unpickle: bool = True, **docker_client_kwargs):
```suggestion
    def __init__(self, mongo_uri=None, db_name="sacred", unpickle: bool = True, **mongo_client_kwargs):
```

Sounds more reasonable.

2022-12-30 16:46 UTC, JarnoRFB commented on incense/experiment_loader.py
> +        client: MongoClient = MongoClient(mongo_uri, **docker_client_kwargs)
```suggestion
        client: MongoClient = MongoClient(mongo_uri, **mongo_client_kwargs)
```

2022-12-30 18:15 UTC, JarnoRFB approved these changes

2022-12-30 18:15 UTC, merged

2022-12-30 18:15 UTC, JarnoRFB commented
@christian-steinmeyer Sorry for the wait, fixed the travis issue now and merged the PR.

2022-12-31 14:47 UTC, JarnoRFB commented
@christian-steinmeyer change was released in v0.0.15

2022-12-31 16:15 UTC, christian-steinmeyer commented
Nice, thanks!